### ISSUE TITLE
Node.js 23 release plan

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/Release#1034]
Hey folks,

According to our schedule, we must release Node.js 23 on Oct 15. I can help on this release but don't think I can commit all my time to it. I suggest we do it as a team effort. These are the tasks we need to do as preparation (feel free to edit this table if I forgot something). Please include your name to the task you can do:

* [x] Create a release branch (v23.x-staging, v23.x) ----- @RafaelGSS 
* [x] Create v23.x labels ----- @RafaelGSS 
* For now on, all `semver-major` PRs should ping @nodejs/tsc.  (cc: @nodejs/issue-triage)
* [x] Create a release proposal - @RafaelGSS (cut-off 2 weeks prior to the release, right after Node.js 22.10.0)
* [x] Generate release candidates
* [x] Create CHANGELOG for v23 (review it with @nodejs/tsc)
* [ ] Create a Node.js blog post for v23 (if we have meaningful changes)
* [x] Create expected assets for v23 (https://github.com/nodejs/build/pull/3915) ----- @richardlau 

cc: @nodejs/releasers

**Comment by RedYetiDev** [comment]
FYI Following this guide, I've pinged the TSC to some semver-major PRs that were recently opened / have had recent activity.

**Comment by joyeecheung** [comment]
Since there is a plan to unflag `require(esm)` on v23, it would be useful to know when the staging branch would be created to coordinate better. There are two more remaining features that should land before it's unflagged (see https://github.com/nodejs/node/issues/52697), but I don't think it would be a huge problem for them to land on v23.1.0 or v23.2.0 (I think as long as we make sure they are backported as a pacakage to LTS, we are good). I am still doing some ecosystem research into what unflagging entails for high-impact npm packages, but for v23 at least I don't think it's vital for it to be very thorough.
