### ISSUE TITLE
make the LTS schedule more accessible

### ISSUE THREAD

**Issue by oe** [nodejs/Release#107]
i've been thinking about this. even though the website home has a link to the LTS schedule graphic, it's still not _the_ most accessible document for figuring out release lines. it has a whole bunch of colors, bars, lines and indicators, and it takes a while to find what you're looking for.

because the most prominent use-case for the schedule is to find out _which version_ and _when that version_ enters LTS and Maintenance, there should be an application to find this information quickly that's also relative to the current date (not absolute, like the graphic).

to be fair, i made something that does this. it can be found at http://nver.tentakel.net/ (source at http://github.com/tentakel/nver). although it's just a prototype right now, i think it makes it a lot easier to understand the release cycles and find the information you're looking for.

so the question is: is this a good method of simplifying the schedule? or is it absolute rubbish and the LTS graphic is better?

**Comment by TheAlphaNerd** [comment]
@tentakel have you seen https://github.com/nodejs/LTS/pull/104?

**Comment by tentakel** [comment]
@TheAlphaNerd yep, but that's still:

- a whole wall of text to read
- a table/diagram with relative dates

although it's simplified (which is good!), it's still not really "easily" accessible

**Comment by boneskull** [comment]
@ore I like it. 

I agree the updated graphic is trying to convey too much information at once. For example: arrows showing what changes go from this place to that, and the presence of "master" at all. I'm also inferring what the arrows mean, because there is no key. I have no idea what the dashed lines mean.

**Comment by mansona** [comment]
Hey folks, I have 2c to weigh in here. I'm currently looking for "versions of node that are still *maintained*" i.e. have not EOL yet. 

Am I right in saying that the only "Active" (i.e. getting security patches) Node versions are v0.10, v0.12, v4.x and v6.x. I know v5.x has officially gone EOL. 

I guess i agree with @Lac on this one, the whole thing is not _clear_ at the moment. My use case: I want to test using Travis on *all supported Node versions* and I just need a list, a simple list of versions that I need to test on. I am not sure if I've interpreted the PNG correctly because of the "LTS Status" doesn't really match with "is currently supported". 

Does this make sense?

**Comment by boneskull** [comment]
Indeed, the above would be helpful for me as well. Are *any* versions of iojs maintained?  I'm guessing no.

**Comment by mansona** [comment]
@boneskull no there aren't any iojs maintained but if I can remember correctly Node 4.x is really not that far from what iojs was. It would be worth doing a 1-for-1 replacement and seeing if you have any issues.

**Comment by drewfish** [comment]
Would it make sense to create a json file which is source-of-truth for version maturity? From that various UI could be created.

**Comment by mansona** [comment]
@drewfish yes, that would be perfect 😄

**Comment by jokeyrhyme** [comment]
Just FYI: I made a package that calculates support dates and ideal LTS versions based on the current plan:
- https://www.npmjs.com/package/nodejs-support-dates
- https://github.com/jokeyrhyme/nodejs-support-dates.js

I plan to build another package for use with CLIs, similar to [update-notifier](https://www.npmjs.com/package/update-notifier), that will notify users when their current Node.js is out of date, and which version they should consider updating to (if appropriate).

**Comment by TheAlphaNerd** [comment]
@nodejs/lts is this something we want to explore or should we close this issue for now?

**Comment by ErisDS** [comment]
If this repository were to include a JSON file, similar to the one shown here: https://github.com/jokeyrhyme/nodejs-support-dates.js/blob/master/lib/versions.json
or here: 
https://github.com/fene/nver/blob/master/ver.json

Then it would automatically be available via the GitHub API, E.g. https://api.github.com/repos/nodejs/LTS/contents/versions.json

That would allow packages like the ones shared in this thread to pull their JSON data from a single source of truth right here at nodejs/LTS, instead of distributing their own information.

This is potentially beneficial, in that anyone can build a tool based on the real data. Whether this is a big enough use case is a question (FYI the 2 packages listed here have ~750 monthly downloads between them) and the major problem is whether or not it would be a challenge to keep it maintained.

For reference, Symfony framework has a little release checker tool: https://symfony.com/roadmap that lets you also grab information in JSON form, however this is not useful for the case of "listing all current versions" although this works: https://symfony.com/roadmap.json?version=all

I'm not particularly for or against as there's already a lot of work for a small group, however creating a single source of truth would probably be a good

**Comment by jokeyrhyme** [comment]
@ErisDS this might be what you're after? https://nodejs.org/dist/index.json

I'm using it myself in https://github.com/jokeyrhyme/update-nodejs-notifier.js

**Comment by ErisDS** [comment]
@jokeyrhyme if that file had all the information you needed, then surely you wouldn't be using https://github.com/jokeyrhyme/nodejs-support-dates.js/blob/master/lib/versions.json? 

For sure, that file could be updated instead of including an extra file here, if that's what you meant.

**Comment by jokeyrhyme** [comment]
@ErisDS true, having all the support schedule dates in with the release date information would be very convenient :)

**Comment by rvagg** [comment]
Hey folks, see #157 for an initial proposal for a JSON schedule, I quite like the idea and can see it coming in very handy.
