### ISSUE TITLE
Proposing April 4th as LTS transition Date

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#264]
This would be both for 6.x to move to Maintenance and 4.x to go EOL

/cc @nodejs/lts @nodejs/tsc

**Comment by jasnell** [comment]
I'm good on this. I'll be starting the plan for the Node.js 10.0.0 release shortly after cutting 9.0.0, I would anticipate 10.0.0 coming out later in the month so having these transition earlier would be good

**Comment by rvagg** [comment]
Could we just formalise EOL as the end of the month in each case rather than an arbitrary date? We've communicate that we drop support "in April" but doing it this early is likely going to be a very big surprise.
Same case could be made for 6.x moving to Maintenance although that matters much less than dropping 4.x support.

@jasnell can you explain how these shifts impact the 10.0.0 release?

**Comment by MylesBorins** [comment]
We have been using the first Tuesday of each month for releases, so I liked
the symmetry for EOL and maintenance bit flip

Open to making it the end of the month though

**Comment by MylesBorins** [comment]
Any more thoughts on this regarding the transition?

**Comment by gibfahn** [comment]
I think end of month makes sense.

**Comment by mhdawson** [comment]
My preference is the end of the month as well.

**Comment by MylesBorins** [comment]
As we have a release scheduled for April 4th does it make sense to simply "transition" the release line without doing it in a release?

**Comment by mhdawson** [comment]
I don't think we actually change anything when we "transition" so unless there is a case were something needs to go in between the 4th and the end of the month simply "transitioning" without a release makes sense to me.
