### ISSUE TITLE
Need help backporting for 8.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#339]
Hey All,

8.x has fallen behind on backports and the project could seriously use support on getting things moving again. If anyone is interested in helping with the backports I'm more than happy to spend a bit of time helping folks figure it out.

**Comment by MylesBorins** [comment]
We should also consider relaxing some of our backporting rules, this is not scaling as it currently exists.

**Comment by MylesBorins** [comment]
Here is a branch diff against v9.x

https://gist.github.com/MylesBorins/078554dfc521fe945a6f45324206ec0e

472 commits to be audited. There are a couple hundred more once we introduce 10.x 😭

**Comment by mhdawson** [comment]
@BethGriggs

**Comment by joyeecheung** [comment]
I looked into backporting commits related to the `lib/internal/bootstrap/node.js` and here is where I am at. 
https://gist.github.com/joyeecheung/52b7dc34b79ce5bd9213ac07f0596b85

To summarize, we have quite a few PRs related to timers/process/bootstrap that theoretically *could* be backported to v8.x (most of them are only on v10.x right now) - and if we skip some of those, it may take a bit more effort to manually backport the rest of them back to v8.x. The question is, how stable do we want the v8.x to be since it's already an active LTS? We need to triage these PRs and make sure we maintain our stability guarantee.

**Comment by MylesBorins** [comment]
@joyeecheung would it be helpful to earmark some time to have a chat or video call to review? I plan to pick up on some of the backports again this week... the next release is supposed to be semver minor so we have some wiggle room this time to do a big update

**Comment by joyeecheung** [comment]
@MylesBorins Sure, I am mostly free this week apart from some meetings in 5pm-7pm UTC. We could also draft a checklist for applying don-land labels (e.g. do not remove properties in active LTS) so that people can follow before landing the PRs.

I can set up a doodle, I guess @addaleax @targos @apapirovski might also be interested?

**Comment by targos** [comment]
I am interested

**Comment by joyeecheung** [comment]
I could also chat after the TSC meeting today, if setting up a doodle seems to be too much overhead

**Comment by MylesBorins** [comment]
Just updated the list

https://gist.github.com/MylesBorins/078554dfc521fe945a6f45324206ec0e

We currently have 1200 commits to be audited 😅

**Comment by joyeecheung** [comment]
@MylesBorins hm I think I understood the original list incorrectly, are we supposed to apply the commits from the bottom to the top? I think my initial investigation was invalid if that's the order and things would be much easier if we can find the commits that block the other commits.

**Comment by MylesBorins** [comment]
@joyeecheung the list is to be applied bottom up.
