### ISSUE TITLE
LTS release proposal for q4 2018 and q1 2019

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#390]
## Q4 2018 Carbon (8.x) Release Schedule

Date | Release
------------ | -------
Nov 20th      | v8.13.0
Dec 4th        | v8.13.1-rc
Dec 18th      | v8.13.1

At the end of Q4 8.x moves to maintenance mode

## Q4 2018 Dubnium (10.x) Release Schedule

Date | Release
------------ | -------
Nov 27th      | v10.14.2-rc
Dec 11th       | v10.14.2
Dec 26th      | v10.14.3-rc

## Q1 2019 Dubnium (10.x) Release Schedule

Date | Release
------------ | -------
Jan 8th         | v10.14.3
Jan 22nd      | v10.14.4-rc
Feb 5th         | v10.14.4
Feb 19th       | v10.14.5-rc
Mar 5th        |  v10.14.5
Mar 19th      |  v10.15.0-rc

**Comment by MylesBorins** [comment]
Does anyone have thoughts about this schedule. Would people be able to volunteer taking responsibility for these specific releases? That would include getting backports up to date and cutting the release / rc's.

Happy to mentor anyone interested in helping out

**Comment by BethGriggs** [comment]
I'll volunteer for v8.13.1, happy to help out with 10.x in Q1 too - maybe we could rotate between releasers when it is just 10.x?

**Comment by MylesBorins** [comment]
@targos do you want to include current releases here too?

**Comment by targos** [comment]
@MylesBorins I think we can open another issue for current releases?

/cc @BridgeAR

**Comment by rvagg** [comment]
Looks good to me. It seems like the aim is for roughly monthly releases but aligned to Tuesdays, I like that.

How about for releaser scheduling we just keep 1 release ahead, so we always know who's doing next. If @BethGriggs, you do the next v8, @codebytere I think might like to do the next v10, then we're 👌. After those releases let's make sure we slot someone in for the next v10.

It looks like @BethGriggs is now on the releaser list. @codebytere do you wanting to move to full releaser status or would you prefer to just do prep?

IMO it might be best for new releasers to do a Current or two before doing an LTS so we're not springing fresh GPG keys on users in LTS. @nodejs/release any thoughts on that as a policy? Does it matter?

**Comment by MylesBorins** [comment]
@codebytere has already been nominated and approved for the release team 🎉

Since they have been working on backports for a couple months now I was
imagining they could work on preparing the release and I could sign /
promote while they Shadow me

They could then promote / sign the following release

Thoughts?

**Comment by rvagg** [comment]
Sounds good, so that'll be 10.13.1. I'd still love to see a Current release signed with a new key before LTS but if the next 10 has your key then we have at least until the 10 after that to have a Current in between if we agree that's the way to go (I'm happy to hear objections as this as a policy).

@codebytere would you like to tackle a Current sometime in the next month or two? We could then assign 10.13.2 as yours, under your key.

@targos I think you should go ahead and open a new issue for discussion about Current. It'd be good to see that surfaced here. I know you have conversations elsewhere about who does which release so visibility into that would be great.

**Comment by MylesBorins** [comment]
Seems reasonable to get a current release out with the key first as a way to test it out. Should we open a PR to document this as part of the on boarding process?

**Comment by rvagg** [comment]
Proposed @ https://github.com/nodejs/Release/pull/393

Also noticed while doing this that:

> New Releasers should wait at least 2 weeks after adding credentials before signing a release

Oops, so we should have got @BethGriggs' key onto README 2 weeks ago.

@codebytere: since you're already approved, you should get yours onto nodejs/node/README.md too and do the bit about informing the Docker team about your GPG key as well if you haven't already so they can get their scripts updated ahead of time.

**Comment by richardlau** [comment]
> Also noticed while doing this that:
> 
> > New Releasers should wait at least 2 weeks after adding credentials before signing a release
> 
> Oops, so we should have got @BethGriggs' key onto README 2 weeks ago.
> 

Myles signed the 8.13.0 release: https://github.com/nodejs/node/pull/24532#issuecomment-440513035

**Comment by MylesBorins** [comment]
@rvagg the way we have been doing it is waiting until they are onboarded to add the keys. As mentioned by richard above I signed the 8.13.0 release. Will review your PR

**Comment by MylesBorins** [comment]
I've updated the release post including info on each person who has volunteered for the release

Closing this issue. We can figure out who is going to do the q1 2019 releases somewhere else
