### ISSUE TITLE
Move meeting times/make release meeting monthly?

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#456]
We've cancelled a few release meeting recently; should we consider moving the meeting time? 
Or perhaps changing it to be monthly rather than every 2 weeks?

**Comment by BridgeAR** [comment]
What about the following:

Up to two days before the meeting we ask if people will join / if it makes sense to have the meeting and if there are less than three persons, we'll cancel it. Otherwise we keep the bi-weekly meetings. That way we can still deal with things fast in case something "urgent" comes up but do not have to block the time if there's nothing to talk about / if not enough people can make it?

**Comment by mhdawson** [comment]
It is better to cancel frequently but hold the slot.  Otherwise if you cancel one you don't have a time to get together for 2 months.

**Comment by BridgeAR** [comment]
So just agreed upon keeping the meetings as they are but ask if a meeting should be cancelled two days before the actual meeting in case too few people said they would join or if there's nothing really to discuss about.

@BethGriggs I hope I summarized it correctly? Please otherwise reopen.
