### ISSUE TITLE
A proposal for changes to LTS

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#458]
I think that we should switch active an maintenance and active time frames for 12.x and on

TL;DR

Current: 6 months
Active LTS: 12 months
Maintenance LTS: 18 months

this would significantly reduce the LTS burden. Thoughts?

**Comment by AdamMajer** [comment]
From distribution point of view (SUSE), switching Active LTS with Maintenance LTS is not a problem. It's actually better from stability point of view. But it would always be a better for distros if Maintenance LTS would be increased. I do understand that this is not always possible due to 3rd party code (OpenSSL, for example)

So no objections here. :+1:

**Comment by mhdawson** [comment]
I'm +1 for the switch provided we are flexible enough to get changes into Maintenance when it makes sense.

**Comment by BridgeAR** [comment]
I suggest we'll discuss this in our next meeting.

**Comment by sam-github** [comment]
+1

**Comment by cjihrig** [comment]
Has this been settled on? Based on https://github.com/nodejs/Release/pull/477 landing, it seems like it has been, and this should be closed.

**Comment by richardlau** [comment]
We need to update the general policy. Here's a PR: https://github.com/nodejs/Release/pull/492
