### ISSUE TITLE
Should we request to have node removed from homebrew?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#486]
Since it isn't a preferred way to install and generally doesn't give LTS by default perhaps we should make an upstream change to homebrew to instead give instructions for a preferred install method e.g. nvm

thoughts?

**Comment by yalefox** [comment]
Yes! Or even if you hit "brew install node" to at least display a message to install via nvm.

**Comment by robbie-mac** [comment]
How is homebrew any different from APT (using the NodeSource Sripts)? They have multiple different avenues of install, Node@8 Node@10. This is a developer having created something that they identified as a need. Instead of squashing it, why not take that as an indication that there is a gap in userland and acknowledge the efforts of a user. Guide them to how they can make their solution better... If you look at their analytics they have a massive amount of use.

**Comment by BridgeAR** [comment]
@MylesBorins I agree that it would be good to remove it from homebrew. We had some discussions around shipping Node.js with a bash script / similar to allow different installers to be used. That way there's no preference for either and the user is still able to easily switch versions. Should we go for something like that?

**Comment by arlac77** [comment]
but only if the nvm installation and usage workflow is straight forward.
Currently it is a mess (at least compared to a simple `brew install node`)

**Comment by paulmillr** [comment]
Absolutely not — nodejs installation is a huge mess everywhere except homebrew-macos & freebsd. E.g. adding sign keys on ubuntu. Why make developers life harder?

I suggest to request home-brew to include nodejs-lts by default and nodejs-latest in a formula like nodejs@12.

**Comment by yalefox** [comment]
Another (better) idea is probably just to have it so it installs properly off homebrew. Instead of images I have an install script that puts all my packages on a new box. Homebrew makes it pretty simple.

**Comment by BridgeAR** [comment]
Should we follow up on this? Is this something we still consider doing? @nodejs/releasers

**Comment by BridgeAR** [comment]
I am closing this, since we never followed up on this.
