### ISSUE TITLE
ESM issue on 12.x requires a quick 12.16.1

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#532]
Hey All. It turns out the backporting of ESM to 12.x introduced a regression, specifically the "self resolution" feature is working without a flag, which is not intentional.

https://github.com/nodejs/node/issues/31754

I want to get a 12.16.1 out today if possible to fix this one problem. Any conerns?

/cc @nodejs/lts @nodejs/tsc

**Comment by richardlau** [comment]
There were a couple of other regressions introduced in 12.16.0 too:
- https://github.com/nodejs/node/issues/31752, which @addaleax is looking at but perhaps we could revert https://github.com/nodejs/node/commit/65e5a8a90cd85fc4d9036bc4b54e0905edd8b51a?
- https://github.com/nodejs/node/issues/31249#issuecomment-585636203 which is due to https://github.com/nodejs/node/pull/30954 landing in 12.16.0. https://github.com/nodejs/node/pull/31547 should fix the regression in building but it hasn't been in a current release yet.

**Comment by MylesBorins** [comment]
PTAL at https://github.com/nodejs/node/pull/31782 which reverts the changes that caused the issues.

**Comment by addaleax** [comment]
@MylesBorins @richardlau 

>     * [nodejs/node#31752](https://github.com/nodejs/node/issues/31752), which @addaleax is looking at but perhaps we could revert [nodejs/node@65e5a8a](https://github.com/nodejs/node/commit/65e5a8a90cd85fc4d9036bc4b54e0905edd8b51a)?

I would strongly prefer not to. This fixed a real bug. A partial revert for the changes in `node_main_instance.cc` should be okay, though.
