### ISSUE TITLE
Rename Current release line Canary?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#537]
It's been a couple years since we've changed the names of things so I figured this might be worth discussing. My personal understanding of the "current" release line is that it gets anything on master that isn't semver-major, and there is a non-trivial chance of bugs / regressions showing up. This is imho a feature of the "current" release line. That said folks are using it in production and I've spoken to a number of people who were unaware that things are not entirely "stable" (the old name for current).

As such I feel a name like "canary" might be more appropriate.

Thoughts?

**Comment by AdamMajer** [comment]
IMHO, people are unaware of a lot of things. They can make themselves aware one way or another. They choose not to.

Having said that, I think renaming Current to some code name, like Canary, is going to be more confusing than not. You will then have to explain what you mean by the code name instead of simply stating the policy for Current.

nodejs.org already has "Recommended for most users" and LTS labels. If someone doesn't know what LTS is, at least they know what "Recommended for most users" means. If they still use 13.x Current, then that's ok but they at least already know it's NOT "recommended for most users".

Also, if you rename the Current to "Unstable" it will just bring in unnecessary angst against using it. The Current is anything but unstable. Node has an exceptionally good test suite. Much better than most of the rest of the open source software. I don't think we need to scare users away from Current just because they are unaware of all details of the clearly documented release cycle.

**Comment by addaleax** [comment]
Yeah, I fully agree with @AdamMajer here.

I also remember that there was resistance against renaming Stable to Current back when we did that – we *do* our best to keep the Current release line stable, and I’m definitely not a fan of renaming it to Canary.

What we should do is find ways to encourage more people to test on Current in addition to LTS. I know that lots of users only test on LTS, sometimes even package authors, but I don’t understand why, to be honest – it just seems like the logical thing to do if you’re also planning to support and run on the next LTS release.
