### ISSUE TITLE
Should we stop publishing changelogs to the nodejs.org website?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#635]
https://github.com/nodejs/node/releases is already a canonical place to find the change logs and arguably has many of the features we might want on the blog such as [an rss feed](https://github.com/nodejs/node/releases.atom).

The primary difference right now is that we do not currently publish that shasums on the release page, but that can easily be rectified. We could also arguably work something into the release script / node-core-utils / github actions to automate the process of making the release entry that contains all the information.

Making this choice would also limit the scope of what needs to be done on nodejs.dev, we could potentially completely remove the blog from the scope of the new website

**Comment by nschonni** [comment]
One minor difference between the GitHub release feed (because I use the current one 😄 ) is that the current one also includes the download links. That's something that could be added to the GitHub releases if it's replacing the page.

One current case I'm not sure how it would work would be the way "security releases" are handled on the blog vs. an only GitHub release approach

**Comment by mhdawson** [comment]
> we could potentially completely remove the blog from the scope of the new website

This would probably warrant broader discussion as I recently had a suggestion that using the website blog instead of medium might get more viewership.

**Comment by ruyadorno** [comment]
Also worth taking into account how disruptive that would be for readers that are used to reaching out to the current blog to get the changelogs for each release. (including me 😳)

**Comment by yoshuawuyts** [comment]
Perhaps it's worth taking a look at how other programming tools approach communication around releases. For example Rust publishes both [a release blog post](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html), and a detailed changelog entry in the `rust-lang/rust` [`RELEASES.md`](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1480-2020-11-19) file. 

The purpose of the blog post is to communicate noteworthy changes made in the latest release to the wider community. With the latter being a point-by-point list of every change made.

Node.js release notes are relatively unapproachable in comparison; making it hard to stay up to date on what's new, and instead leaving it up to users to discover why they should care about the changes made. Rather than deprecating the web version of the release notes, I'd love for Node to instead use that opportunity to communicate in more depth about the changes in that release.

That way it no longer feels like a bunch of duplication between where releases are shared, and instead each can be more clearly tuned for a specific audience.

**Comment by targos** [comment]
@yoshuawuyts That's a good point, and something that's already been discussed before. In my opinion, the problem with Node.js release notes is not the medium, though. It's that we do not have good process to prepare them with the help of all collaborators before doing the actual release, so the job is entirely up to the releasers and they already have a lot to do.
I've been trying myself to create more user-friendly changelogs ([example](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#2020-11-04-version-1510-current-targos)) and while I don't know if it has been successful, I think it is possible to use the same format in the blog posts and in the changelog files (People who are not interested in the detailed list can stop reading after the notable changes section).

**Comment by aduh95** [comment]
One thing to consider is that not everyone has access to GitHub (E.G.: people in Iran), while the website is open to everyone (I think, unless we have restrictions there too?).

**Comment by nickmccurdy** [comment]
FWIW GitHub's restrictions against Iran are going away. https://github.blog/2021-01-05-advancing-developer-freedom-github-is-fully-available-in-iran/

**Comment by BethGriggs** [comment]
Could this be closed? It's a fairly old issue and I do not believe we intend to stop publishing changelogs to the nodejs.org website.

(There are some enhancements mentioned in this thread, but I believe that's a separate topic likely covered by https://github.com/nodejs/Release/issues/568.)

**Comment by targos** [comment]
![image](https://user-images.githubusercontent.com/2352663/167780737-8e3ad483-bd21-42c1-b7fb-83c496657f78.png)

@MylesBorins how did you do that?
