### ISSUE TITLE
Change "Current" to "Beta"

### ISSUE THREAD

**Issue by pongo** [nodejs/Release#636]
Many people think that the "Current" version is the actual stable version. In fact, it is a beta version.

I suggest renaming "Current" to "Beta" to avoid misunderstandings.

**Comment by targos** [comment]
"Current" is not a beta version. It is stable.

**Comment by begin-again** [comment]
Does stable mean safe for production?

**Comment by AdamMajer** [comment]
> Does stable mean safe for production?

Sure. The purpose of "Current" is that the API can be changed more aggressively than the "LTS". If something is not stable, it's generally marked as "experimental" that requires extra switches to turn on. Everything is defined very clearly on the front page here (https://github.com/nodejs/Release) in the REDME.md. You just have to read it.

**Comment by mhdawson** [comment]
@begin-again the answer depends on the balance you want to strike between having the latest features and risk.  I'm more conservative so personally I recommend LTS for production but depending on the situation others will be comfortable using Current.

**Comment by begin-again** [comment]
I get that, but like @pongo  mentioned "current" seems like that is the one people should be using. For instance if one goes to the NodeJS.org site, it seems that current is what I would want because it has "latest features". It would be nicer I think to either call it beta as suggested or include a statement that the latest features my be behind flags.

![image](https://user-images.githubusercontent.com/11179873/103584937-3e37ff80-4eb0-11eb-943b-7a3829b3b167.png)

On a side note, how does one find which features are behind flags? Is it a mater of grepping the command line?

v15.4.0
```script
$ node --help | grep "\-\-experiment"
  --experimental-import-meta-resolve
  --experimental-json-modules experimental JSON interop support for
  --loader, --experimental-loader=...
  --experimental-policy=...   use the specified file as a security
  --experimental-repl-await   experimental await keyword support in
  --es-module-specifier-resolution, --experimental-specifier-resolution=...
  --experimental-vm-modules   experimental ES Module support in vm
  --experimental-wasi-unstable-preview1
  --experimental-wasm-modules experimental ES Module support for
```

**Comment by targos** [comment]
There are also many features behind a flag in LTS versions.
What is special about Current in general is that it gets updates more frequently than LTS.

**Comment by begin-again** [comment]
I think that is what we want to convey better. If I'm using LTS of say v12.15.0, i can safely upgrade to the latest version of 12.20.1 even if I am using an experimental flag. Not so with current correct? (its not guaranteed to have same api between versions). If I'm on current and I want to upgrade, I need to read the change logs carefully.

**Comment by mhdawson** [comment]
Current is still covered by SemVer. Having said that Experimental means that there are no guarantees for any version even if we are generally conservative.

**Comment by MylesBorins** [comment]
As mentioned above "Current" is definitely not beta. It follows SemVer and is an official release. The update cadence and stability guarantees are the biggest difference. Some currents (the even versions) become LTS.

> I get that, but like @pongo mentioned "current" seems like that is the one people should be using.

The image you shared says "Recommended for most users" under the LTS version, which seems to me like it is saying it is the one people should be using.

I spend a few minutes staring at the line and trying to think of a better way to frame things but really couldn't come up with something. I don't think we should change the name of the release lines, but we could change the tagline on the website

e.g.

LTS: Recommended for most users
Current: Latest Features, AT A PRICE

**Comment by targos** [comment]
Maybe it would be a good idea to add a line below each release with the end of support date? Personally, I usually do not recommend to use odd-numbered Current releases in production, not because they are unstable, but because support doesn't last long enough. I have no problem recommending and using myself even-numbered Current releases.

With the new info, today it would look like this:

| 14.15.4 LTS | 15.5.1 Current |
|:---:|:---:|
| Recommended For Most Users | Latest Features |
| Supported until April 2023 | Supported until June 2021 |

**Comment by pongo** [comment]
We should decide if "Current" is **really** ready for production?

Maybe:

LTS: Best for production
Current: Latest Features, not ready for production

**Comment by aduh95** [comment]
> Current: Latest Features, not ready for production

But Current is ready for production. I agree with what was said above, the issue for most users would be the update cadence, and the short term support for odd version numbers.

Also sometimes library authors are slow to fix issues specific to Node.js Current versions, I have the feeling that calling them "beta" would worsen the situation rather than improve it.

**Comment by jsumners** [comment]
Given no discussion for almost a year, I suspect this can be closed.

**Comment by mhdawson** [comment]
I agreed that we should close this out. Please let us know if you think that was not the right thing to do.
