### ISSUE TITLE
http request smuggling vulnerability in Node.js

### ISSUE THREAD

**Issue by nagasaipa-Kore** [nodejs/Release#799]
The llhttp parser in node.js core (v14.20.1, <v16.17.1 and <v18.9.1) in the http module of Node.js does not strictly use the CRLF sequence to delimit HTTP requests. This can lead to HTTP Request Smuggling (HRS). We are using Node.js V14.18.0 and need a fix for this issue.  as HTTP request smuggling involves interfering with the way HTTP servers process HTTP requests. If server is vulnerable to HTTP request smuggling, it will forward irregular HTTP requests to the back end.

Please help us with in which version of Node.js this issue will be fixed, if it is already fixed, please comment with the specific version.

**Comment by mhdawson** [comment]
I think you are asking about what version a fix was made. You can read about updates in each version in the changelog:

https://nodejs.org/en/blog/

There is only one stream for each LTS line. You should update to the latest V14.x line to be up to date on security patches. In that sense you may have already answered your questions.  You need to update to at least  v14.20.1 if you meant to have < for all of the versions listedc above.

If instead you are reporting an issue you believe has not been fixerd, please report as outined in the projects Security.md file - https://github.com/nodejs/node/blob/main/SECURITY.md

**Comment by ruyadorno** [comment]
The original description makes me think of one of the vulnerabilities that was fixed in the latest security releases (v16.20.1, v18.16.1, v20.3.1) (ref: https://nodejs.org/en/blog/vulnerability/june-2023-security-releases#http-request-smuggling-via-empty-headers-separated-by-cr-(medium)-(cve-2023-30589)).

In the future please refer to the appropriate channels to disclosure potential vulnerabilities, as pointed out by @mhdawson above, you can find more info in the `SECURITY.md` docs (ref: https://github.com/nodejs/node/blob/main/SECURITY.md).
